// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "amplifyreactapp-20181108133237--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://amplifyreactapp-20181108133237--hostingbucket.s3-website.us-east-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-2:ad4ee9af-d96e-4a33-9192-9aa99700d11f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_XnWsbDyLs",
    "aws_user_pools_web_client_id": "14sb2j2ohd7l2ceklnljf0d9pb",
    "aws_mobile_analytics_app_id": "4e32ea748e414334b1e8e3159b08ac5a",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "amplifyreactapp4230056b6b724cd8a5462d9feb299b0f",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "itemstable",
            "region": "us-east-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://l27e7g6z4vboznai67vb7hvsoi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "myitems",
            "endpoint": "https://th7694v407.execute-api.us-east-2.amazonaws.com/Prod",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
